default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: websocket_demo_development

test:
  <<: *default
  database: websocket_demo_test

production:
  <<: *default
  database: websocket_demo_production
#  username: websocket_demo
#  password: <%= ENV['MI-BACKEND_DATABASE_PASSWORD'] %>
